<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LavoratoriSeeder extends Seeder
{
    public function run()
    {
        DB::table('lavoratori')->insert([
            [
                'nome' => 'Domenica',
                'cognome' => 'Angelone',
                'codice_fiscale' => 'AAAAAAA01',
                'telefono' => '3333333301',
                'email' => 'angelone@phonect.it',
                'data_nascita' => '1964-10-17',
                'data_assunzione' => '2007-01-15',
                'attivo' => true,
            ],
            [
                'nome' => 'Olimpio',
                'cognome' => 'Bornaschella',
                'codice_fiscale' => 'AAAAAAA02',
                'telefono' => '3333333302',
                'email' => 'aaa@bbb.com1',
                'data_nascita' => '1975-08-19',
                'data_assunzione' => '2020-01-07',
                'attivo' => true,
            ],
            [
                'nome' => 'Adele',
                'cognome' => 'Cardines',
                'codice_fiscale' => 'AAAAAAA03',
                'telefono' => '3333333303',
                'email' => 'aaa@bbb.com2',
                'data_nascita' => '1975-06-29',
                'data_assunzione' => '2009-11-19',
                'attivo' => true,
            ],
            [
                'nome' => 'Nicandro',
                'cognome' => 'Cimorelli',
                'codice_fiscale' => 'AAAAAAA04',
                'telefono' => '3333333304',
                'email' => 'aaa@bbb.com3',
                'data_nascita' => '1987-10-15',
                'data_assunzione' => '2015-02-02',
                'attivo' => true,
            ],
            [
                'nome' => 'Sabatino',
                'cognome' => 'Del Riccio',
                'codice_fiscale' => 'AAAAAAA05',
                'telefono' => '3333333305',
                'email' => 'aaa@bbb.com4',
                'data_nascita' => '1982-09-08',
                'data_assunzione' => '2010-10-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Sonia',
                'cognome' => 'Faccenda',
                'codice_fiscale' => 'AAAAAAA06',
                'telefono' => '3333333306',
                'email' => 'aaa@bbb.com5',
                'data_nascita' => '1978-01-08',
                'data_assunzione' => '1998-01-26',
                'attivo' => true,
            ],
            [
                'nome' => 'Michele',
                'cognome' => 'Forte',
                'codice_fiscale' => 'AAAAAAA07',
                'telefono' => '3333333307',
                'email' => 'aaa@bbb.com6',
                'data_nascita' => '1970-12-06',
                'data_assunzione' => '2007-10-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Raffaella',
                'cognome' => 'Gervasio',
                'codice_fiscale' => 'AAAAAAA08',
                'telefono' => '3333333308',
                'email' => 'aaa@bbb.com7',
                'data_nascita' => '1970-04-16',
                'data_assunzione' => '1998-01-05',
                'attivo' => true,
            ],
            [
                'nome' => 'Carmela',
                'cognome' => 'Giannini',
                'codice_fiscale' => 'AAAAAAA09',
                'telefono' => '3333333309',
                'email' => 'aaa@bbb.com8',
                'data_nascita' => '1969-06-06',
                'data_assunzione' => '2001-02-12',
                'attivo' => true,
            ],
            [
                'nome' => 'Luigi',
                'cognome' => 'Greco',
                'codice_fiscale' => 'AAAAAAA10',
                'telefono' => '3333333310',
                'email' => 'aaa@bbb.com9',
                'data_nascita' => '1995-12-28',
                'data_assunzione' => null,
                'attivo' => true,
            ],
            [
                'nome' => 'Silvana',
                'cognome' => 'Greco',
                'codice_fiscale' => 'AAAAAAA11',
                'telefono' => '3333333311',
                'email' => 'aaa@bbb.com10',
                'data_nascita' => '1960-04-29',
                'data_assunzione' => '1998-01-05',
                'attivo' => true,
            ],
            [
                'nome' => 'Fiorella',
                'cognome' => 'Iannacone',
                'codice_fiscale' => 'AAAAAAA12',
                'telefono' => '3333333312',
                'email' => 'aaa@bbb.com11',
                'data_nascita' => '1973-02-02',
                'data_assunzione' => '2009-11-19',
                'attivo' => true,
            ],
            [
                'nome' => 'Giovanni',
                'cognome' => 'Iannarelli',
                'codice_fiscale' => 'AAAAAAA13',
                'telefono' => '3333333313',
                'email' => 'aaa@bbb.com12',
                'data_nascita' => '1989-04-14',
                'data_assunzione' => null,
                'attivo' => true,
            ],
            [
                'nome' => 'Palmerino',
                'cognome' => 'Iannetta',
                'codice_fiscale' => 'AAAAAAA14',
                'telefono' => '3333333314',
                'email' => 'aaa@bbb.com13',
                'data_nascita' => '1993-12-13',
                'data_assunzione' => '2018-03-05',
                'attivo' => true,
            ],
            [
                'nome' => 'Claudia',
                'cognome' => 'Marinelli',
                'codice_fiscale' => 'AAAAAAA15',
                'telefono' => '3333333315',
                'email' => 'aaa@bbb.com14',
                'data_nascita' => '1970-10-03',
                'data_assunzione' => '2009-11-02',
                'attivo' => true,
            ],
            [
                'nome' => 'Franca',
                'cognome' => 'Martone',
                'codice_fiscale' => 'AAAAAAA16',
                'telefono' => '3333333316',
                'email' => 'aaa@bbb.com15',
                'data_nascita' => '1972-04-17',
                'data_assunzione' => '1998-02-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Antonella',
                'cognome' => 'Masella',
                'codice_fiscale' => 'AAAAAAA17',
                'telefono' => '3333333317',
                'email' => 'aaa@bbb.com16',
                'data_nascita' => '1973-02-11',
                'data_assunzione' => '2010-03-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Paolo',
                'cognome' => 'Migliozzi',
                'codice_fiscale' => 'AAAAAAA18',
                'telefono' => '3333333318',
                'email' => 'quality@phonect.it',
                'data_nascita' => '1974-02-26',
                'data_assunzione' => '2013-03-05',
                'attivo' => true,
            ],
            [
                'nome' => 'Daniele',
                'cognome' => 'Neri',
                'codice_fiscale' => 'AAAAAAA19',
                'telefono' => '3333333319',
                'email' => 'danieleneri070@gmail.com',
                'data_nascita' => '1986-04-03',
                'data_assunzione' => '2012-01-12',
                'attivo' => true,
            ],
            [
                'nome' => 'Marianna',
                'cognome' => 'Pio',
                'codice_fiscale' => 'AAAAAAA20',
                'telefono' => '3333333320',
                'email' => 'aaa@bbb.com17',
                'data_nascita' => '1977-01-03',
                'data_assunzione' => '2009-11-17',
                'attivo' => true,
            ],
            [
                'nome' => 'Filomena',
                'cognome' => 'Pontone',
                'codice_fiscale' => 'AAAAAAA21',
                'telefono' => '3333333321',
                'email' => 'aaa@bbb.com18',
                'data_nascita' => '1972-11-12',
                'data_assunzione' => '2010-11-17',
                'attivo' => true,
            ],
            [
                'nome' => 'Antonio',
                'cognome' => 'Riccio',
                'codice_fiscale' => 'AAAAAAA22',
                'telefono' => '3333333322',
                'email' => 'aaa@bbb.com19',
                'data_nascita' => '1994-12-15',
                'data_assunzione' => '2021-01-18',
                'attivo' => true,
            ],
            [
                'nome' => 'Italia',
                'cognome' => 'Romano',
                'codice_fiscale' => 'AAAAAAA23',
                'telefono' => '3333333323',
                'email' => 'aaa@bbb.com20',
                'data_nascita' => '1963-11-03',
                'data_assunzione' => '2007-04-19',
                'attivo' => true,
            ],
            [
                'nome' => 'Pina',
                'cognome' => 'Romano',
                'codice_fiscale' => 'AAAAAAA24',
                'telefono' => '3333333324',
                'email' => 'aaa@bbb.com21',
                'data_nascita' => '1961-06-08',
                'data_assunzione' => '2010-07-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Roberto',
                'cognome' => 'Rossi',
                'codice_fiscale' => 'AAAAAAA25',
                'telefono' => '3333333325',
                'email' => 'aaa@bbb.com22',
                'data_nascita' => '1974-04-28',
                'data_assunzione' => '2007-01-08',
                'attivo' => true,
            ],
            [
                'nome' => 'Nicandro',
                'cognome' => 'Scarabeo',
                'codice_fiscale' => 'AAAAAAA26',
                'telefono' => '3333333326',
                'email' => 'aaa@bbb.com23',
                'data_nascita' => '1990-08-09',
                'data_assunzione' => '2024-09-02',
                'attivo' => true,
            ],
            [
                'nome' => 'Antonella',
                'cognome' => 'Silvestri',
                'codice_fiscale' => 'AAAAAAA27',
                'telefono' => '3333333327',
                'email' => 'aaa@bbb.com24',
                'data_nascita' => '1971-04-04',
                'data_assunzione' => '2008-11-17',
                'attivo' => true,
            ],
            [
                'nome' => 'Rosa',
                'cognome' => 'Silvestri',
                'codice_fiscale' => 'AAAAAAA28',
                'telefono' => '3333333328',
                'email' => 'aaa@bbb.com25',
                'data_nascita' => '1977-04-19',
                'data_assunzione' => '2011-01-13',
                'attivo' => true,
            ],
            [
                'nome' => 'Antonio',
                'cognome' => 'Tallarico',
                'codice_fiscale' => 'AAAAAAA29',
                'telefono' => '3333333329',
                'email' => 'account@phonect.it',
                'data_nascita' => '1978-11-04',
                'data_assunzione' => '2015-09-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Samir',
                'cognome' => 'Toumir',
                'codice_fiscale' => 'AAAAAAA30',
                'telefono' => '3333333330',
                'email' => 'aaa@bbb.com26',
                'data_nascita' => '1986-03-02',
                'data_assunzione' => '2018-02-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Filomena',
                'cognome' => 'Varone',
                'codice_fiscale' => 'AAAAAAA31',
                'telefono' => '3333333331',
                'email' => 'aaa@bbb.com27',
                'data_nascita' => '1968-11-13',
                'data_assunzione' => '2008-11-17',
                'attivo' => true,
            ],
            [
                'nome' => 'Ivana ',
                'cognome' => 'Venditti',
                'codice_fiscale' => 'AAAAAAA32',
                'telefono' => '3333333332',
                'email' => 'aaa@bbb.com28',
                'data_nascita' => '1973-10-01',
                'data_assunzione' => '2011-09-01',
                'attivo' => true,
            ],
            [
                'nome' => 'Mirella',
                'cognome' => 'Verducci',
                'codice_fiscale' => 'AAAAAAA33',
                'telefono' => '3333333333',
                'email' => 'aaa@bbb.com29',
                'data_nascita' => '1967-10-29',
                'data_assunzione' => '2008-11-17',
                'attivo' => true,
            ],
        ]);
    }
}
